### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by jonmalave** [daveismynamecom/dropboxbackup#2]
In line 12 of index.php when trying to add a filename to test upload, I get a HTTP ERROR 500. 

I am trying to upload a single README.md file that resides in the same directory where I am executing the index.php to process the upload to dropbox. 

`$bk->upload('README.md'); //file or folder to upload to dropbox`

that's my code... if I remove the README.md and just leave the upload function empty with no params, the index.php runs fine and says Upload Complete.

**Note:** I am using PHP 7.0,  I don't know if this might be part of the issue? 

Please help!

**Comment by wilson382** [comment]
Jonnmalave, this script is deprecated if I'm not mistaken. This is because the Dropbox api v1 was discontinued from Dropbox. In order to make this work a migration need to be done to api v2.

**Comment by jonmalave** [comment]
but it seems @daveismyname just updated the README.md 2 days ago... so i'm just guessing it still works lol! Anyway if there are any alternatives like this would be great to link us too then...

**Comment by wilson382** [comment]
No, he actually updated the README.md file because I pointed out that the links were working.

**Comment by wilson382** [comment]
I'm also looking for an alternative to this, since I found the Google api difficult to follow. If you find anything please let me know.

**Comment by dcblogdev** [comment]
Yes, this is since dropbox api  1.1 will no longer work.

I've created a new branch https://github.com/daveismyname/dropboxbackup/tree/dropbox-v2 this uses a new api wrapper from https://github.com/spatie/dropbox-api

now on index.php you don't need the `$project` only the token and the folder to upload to.

I'll update my tutorial soon. 

Oh this will only work with php 7 or higher.

**Comment by jonmalave** [comment]
@daveismyname awesome, thank you so much! 

this appears to be working just fine now.... it works, but I don't see or know of where I can set the option to overwrite existing data! is that still possible with the new version?

**Comment by dcblogdev** [comment]
Looking at the docs https://www.dropbox.com/developers/documentation/http/documentation#files-upload

you can set the mode to one of these:

```
add Void Do not overwrite an existing file if there is a conflict. The autorename strategy is to append a number to the file name. For example, "document.txt" might become "document (2).txt".

overwrite Void Always overwrite the existing file. The autorename strategy is the same as it is for add.

update String(min_length=9, pattern="[0-9a-f]+") Overwrite if the given "rev" matches the existing file's "rev". The autorename strategy is to append the string "conflicted copy" to the file name. For example, "document.txt" might become "document (conflicted copy).txt" or "document (Panda's conflicted copy).txt".
```

The default in this script is `add`.

In backup.php alter the upload method add a third param of mode:

```
public function uploadFile($file){
    $this->dbxClient->upload("/".$this->projectFolder."/$file", file_get_contents($file), 'overwrite');
}
```

**Comment by dcblogdev** [comment]
I've just updated the upload method to use named params:

```php
public function uploadFile($file, $mode = 'add')
	{
		$path = "/".$this->projectFolder."/$file";
		$contents = file_get_contents($file);
	    $this->dbxClient->upload($path, $contents, $mode);
	}
```

This way you can set the mode when you call upload:

```
$bk->upload('test.txt', 'overwrite');
```

This will overwrite and if the mode param is not passed then add will be used.

**Comment by jonmalave** [comment]
very nice!! that's super cool... thanks again!!!

I do have another thing to report... I notice that if we encounter a blank file, we will return an HTTP Error 500. You can test this yourself by making the test.txt file blank.

**Comment by jonmalave** [comment]
It seems this is working for me to skip the blank files 

`if($contents !== '') {
  $this->dbxClient->upload($path, $contents, $mode);			
 }`

**Comment by dcblogdev** [comment]
Yes you can do that or like this:

```php
public function uploadFile($file, $mode = 'add')
{
    $path = "/".$this->projectFolder."/$file";
    $contents = file_get_contents($file);

    //if the contents is not empty upload otherwise do nothing
    if (! empty($contents)) {
        $this->dbxClient->upload($path, $contents, $mode);
    }
}
```

**Comment by dcblogdev** [comment]
If you want to be able to upload blank files it may be worth opening an issue on https://github.com/spatie/dropbox-api/issues as that's what this is using to interact with Dropbox.

**Comment by jonmalave** [comment]
@daveismyname thanks again for this amazing script! I really appreciate it... it's working well!
